### PR TITLE
remove jenkinsfile

### PR DESCRIPTION
**Pull request by rtewalt**
| Status  | Type  | Migrations
| :---: | :---: | :---: |
| Ready/In Development/Hold | Feature/Bug/Chore/Release/Hotfix | Yes/No |

## Description

_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR?_

## Other changes

_List other affected areas of the application (e.g. small bug fixes not in their own ticket, UI tweaks, refactors) also included in this PR_

## Related Tickets

List related Clubhouse tickets:

* [insert ticket name here](insert link here)

## Todos

_Fill out or remove list items as needed_

- [ ] Tests
- [ ] Documentation

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
db migrations, new dependencies, etc._

### CODE REVIEW

**Comment by rtewalt** [comment]
test this please

**Comment by mtburell** [comment]
Can one of the admins verify this patch?

**Comment by rtewalt** [comment]
@mtburell i'm just trying to setup PR building for this repo, but sure, who would you like to review?

**Comment by rtewalt** [comment]
test this please

**Comment by rtewalt** [comment]
retest this please

**Pull request closed without merging**
